"use client";

import SectionCard from "@/components/forms/SectionCard";
import CheckboxGroup from "@/components/forms/CheckboxGroup";

import {
  MATERIAL_CATEGORIES,
  BUSINESS_MATERIALS,
  toCheckboxOptions,
} from "./constants";

interface MaterialCategoriesSectionProps {
  businessProfileType: string;

  materialCategories: string[];

  errors: Record<string, string>;

  setMaterialCategories: (
    values: string[],
    clickedValue?: string
  ) => void;
}

export default function MaterialCategoriesSection({
  businessProfileType,
  materialCategories,
  errors,
  setMaterialCategories,
}: MaterialCategoriesSectionProps) {
  return (
    <SectionCard
      title="Recyclable Materials Generated"
      description="Select the recyclable materials typically generated by your business."
    >
      <CheckboxGroup
        label="Recyclable Materials Generated"
        required
        values={materialCategories}
        options={toCheckboxOptions(
  BUSINESS_MATERIALS[businessProfileType] ??
    MATERIAL_CATEGORIES
)}
        onChange={setMaterialCategories}
        error={errors.materialCategories}
      />
    </SectionCard>
  );
}